language: elixir
matrix:
  include:
    - otp_release: 18.3
      elixir: 1.3.2
    - otp_release: 19.0
      elixir: 1.3.2
sudo: false
before_script:
  - mix deps.get --only test
script:
  - "MIX_ENV=test mix credo --strict && MIX_ENV=test mix coveralls.travis"
